plan = Plan.create(name: 'Новичок')
plan.exercises.create(title: 'Знакомство с лыжами', description: 'Необходимо полностью экипироваться и проехать 1 км на лыжах.', order: 1)
plan.exercises.create(title: 'Знакомство: Попеременный двухшажный ход', description: 'Проехать 1 км используя попеременный двухшажный ход', order: 2)
plan.exercises.create(title: 'Знакомство: Одновременный бесшажный ход', description: 'Проехать 1 км используя одновременный бесшажный ход', order: 3)
plan.exercises.create(title: 'Знакомство: Полуконьковый ход', description: 'Проехать 1 км используя полуконьковый ход', order: 4)

plan = Plan.create(name: 'Продолжающий')
plan.exercises.create(title: 'Велокросс', description: 'Проехать 15 км на велосипеде', order: 1)
plan.exercises.create(title: 'Полуконьковый ход на 5 км', description: 'Проехать 5 км используя полуконьковый ход', order: 2)
plan.exercises.create(title: 'Тренировка в зале', description: 'Занятие с гирями и штангами для укрепления рук', order: 3)
plan.exercises.create(title: 'Полуконьковый ход на 10 км', description: 'роехать 10 км используя полуконьковый ход', order: 4)
plan.exercises.create(title: 'Велокросс на выносливость', description: 'Проехать 30 км на велосипеде', order: 5)
plan.exercises.create(title: 'Спортивная ходьба', description: 'Пройти 3 км', order: 6)

plan = Plan.create(name: 'Продвинутый')
plan.exercises.create(title: 'Велокросс', description: 'Проехать 15 км на велосипеде', order: 1)
plan.exercises.create(title: 'Полуконьковый ход на 5 км', description: 'Проехать 5 км используя полуконьковый ход', order: 2)
plan.exercises.create(title: 'Тренировка в зале: день рук', description: 'Занятие с гирями и штангами для укрепления рук', order: 3)
plan.exercises.create(title: 'Полуконьковый ход на 10 км', description: 'роехать 10 км используя полуконьковый ход', order: 4)
plan.exercises.create(title: 'Велокросс на выносливость', description: 'Проехать 30 км на велосипеде', order: 5)
plan.exercises.create(title: 'Спортивная ходьба', description: 'Пройти 3 км', order: 6)
plan.exercises.create(title: 'Тренировка в зале: день ног', description: 'Занятие для развития мышечной массы на ногах', order: 7)
plan.exercises.create(title: 'Полуконьковый ход на 15 км', description: 'Проехать 15 км используя полуконьковый ход', order: 8)
